### ISSUE TITLE
Can we have a release of the master branch with support to Rails 5?

### ISSUE THREAD

**Issue by rafaelfranca** [lightyear/sql-logging#18]
3.0.9 is locking the Rails version to < 5 even that in the commit that bump the gem to that version the gemspec doesn't have that lock. I guess it was manually built when released.

Can we have a new release?

**Comment by tjoyal** [comment]
I've just released 3.0.10 (https://rubygems.org/gems/sql-logging/versions/3.0.10)

There is not a lot of tests but a quick 🎩 seems to be working as expected on Rails5.
