### ISSUE TITLE
No backtraces for Rails 5

### ISSUE THREAD

**Issue by vemv** [lightyear/sql-logging#19]
Hi there!

First of all thanks for this gem, it's been my trusty tool for some 3 years!

Lately I started using it for Rails 5 and I noticed it doesn't backtrace the origin code path for a given query, anymore

What could have changed with Rails 5?

**Comment by tjoyal** [comment]
I've been playing a little bit with it and it seems to still be reporting backtrace on a fairly fresh rails 5 project.

> Lately I started using it for Rails 5 and I noticed it doesn't backtrace the origin code path for a given query, anymore

Can you precise? Does it not display stacktrace at all or simply missing some of the expected trace?

The stack is cleaned via `Rails.backtrace_cleaner` by default:
https://github.com/lightyear/sql-logging/blob/081da303cfd1a49445b946cd51e320d4d52f9642/lib/sql-logging/configuration.rb#L38

Also the logger defaults to `Rails.logger`
https://github.com/lightyear/sql-logging/blob/081da303cfd1a49445b946cd51e320d4d52f9642/lib/sql-logging/configuration.rb#L31-L33
and the logger level must be set to `debug`
https://github.com/lightyear/sql-logging/blob/081da303cfd1a49445b946cd51e320d4d52f9642/lib/sql-logging/statistics.rb#L56

I would need more information to help you further.
